import pandas as pd

mlb_df = pd.DataFrame([
    {"Rank": 116, "Player": "Byron Buxton", "Team": "MIN", "OBP": 0.298},
    {"Rank": 117, "Player": "Kerry Carpenter", "Team": "DET", "OBP": 0.297},
    {"Rank": 118, "Player": "Trey Sweeney", "Team": "DET", "OBP": 0.296},
    {"Rank": 119, "Player": "Tommy Edman", "Team": "LAD", "OBP": 0.295},
    {"Rank": 120, "Player": "Brenton Doyle", "Team": "COL", "OBP": 0.294},
    {"Rank": 120, "Player": "Otto Lopez", "Team": "MIA", "OBP": 0.294},
    {"Rank": 122, "Player": "Jorge Soler", "Team": "LAA", "OBP": 0.291},
    {"Rank": 123, "Player": "Michael Conforto", "Team": "LAD", "OBP": 0.291},
    {"Rank": 124, "Player": "Wilmer Flores", "Team": "SF", "OBP": 0.288},
    {"Rank": 125, "Player": "Gunnar Henderson", "Team": "BAL", "OBP": 0.286},
    {"Rank": 126, "Player": "Eugenio Suárez", "Team": "AZ", "OBP": 0.286},
    {"Rank": 127, "Player": "Shea Langeliers", "Team": "ATH", "OBP": 0.285},
    {"Rank": 128, "Player": "Mark Vientos", "Team": "NYM", "OBP": 0.283},
    {"Rank": 129, "Player": "Luis García", "Team": "WSH", "OBP": 0.283},
    {"Rank": 130, "Player": "Spencer Steer", "Team": "CIN", "OBP": 0.281},
    {"Rank": 131, "Player": "Ryan McMahon", "Team": "COL", "OBP": 0.280},
    {"Rank": 132, "Player": "Salvador Perez", "Team": "KC", "OBP": 0.280},
    {"Rank": 133, "Player": "Brandon Nimmo", "Team": "NYM", "OBP": 0.279},
    {"Rank": 134, "Player": "Triston Casas", "Team": "BOS", "OBP": 0.277},
    {"Rank": 135, "Player": "Matt McLain", "Team": "CIN", "OBP": 0.275},
    {"Rank": 136, "Player": "Junior Caminero", "Team": "TB", "OBP": 0.273},
    {"Rank": 137, "Player": "Lenyn Sosa", "Team": "CWS", "OBP": 0.271},
    {"Rank": 138, "Player": "Cody Bellinger", "Team": "NYY", "OBP": 0.270},
    {"Rank": 139, "Player": "Ceddanne Rafaela", "Team": "BOS", "OBP": 0.270},
    {"Rank": 139, "Player": "Jordan Walker", "Team": "STL", "OBP": 0.270},
    {"Rank": 141, "Player": "Brooks Baldwin", "Team": "CWS", "OBP": 0.270},
    {"Rank": 142, "Player": "Anthony Santander", "Team": "TOR", "OBP": 0.270},
    {"Rank": 143, "Player": "Marcus Semien", "Team": "TEX", "OBP": 0.269},
    {"Rank": 144, "Player": "Jackson Chourio", "Team": "MIL", "OBP": 0.268},
    {"Rank": 145, "Player": "Christian Walker", "Team": "HOU", "OBP": 0.266},
    {"Rank": 146, "Player": "Austin Wells", "Team": "NYY", "OBP": 0.265},
    {"Rank": 147, "Player": "Andrés Giménez", "Team": "TOR", "OBP": 0.265},
    {"Rank": 148, "Player": "Mike Trout", "Team": "LAA", "OBP": 0.264},
    {"Rank": 149, "Player": "Dansby Swanson", "Team": "CHC", "OBP": 0.262},
    {"Rank": 150, "Player": "Adolis García", "Team": "TEX", "OBP": 0.262},
    {"Rank": 151, "Player": "Alec Bohm", "Team": "PHI", "OBP": 0.254},
    {"Rank": 152, "Player": "Luis Rengifo", "Team": "LAA", "OBP": 0.252},
    {"Rank": 153, "Player": "Joey Ortiz", "Team": "MIL", "OBP": 0.252},
    {"Rank": 154, "Player": "Carlos Correa", "Team": "MIN", "OBP": 0.248},
    {"Rank": 155, "Player": "Dylan Crews", "Team": "WSH", "OBP": 0.248},
    {"Rank": 156, "Player": "Tommy Pham", "Team": "PIT", "OBP": 0.248},
    {"Rank": 157, "Player": "Brandon Lowe", "Team": "TB", "OBP": 0.246},
    {"Rank": 158, "Player": "Michael Toglia", "Team": "COL", "OBP": 0.244},
    {"Rank": 159, "Player": "Ryan Mountcastle", "Team": "BAL", "OBP": 0.243},
    {"Rank": 160, "Player": "Yainer Diaz", "Team": "HOU", "OBP": 0.240},
    {"Rank": 161, "Player": "Vinnie Pasquantino", "Team": "KC", "OBP": 0.239},
    {"Rank": 162, "Player": "Michael Harris", "Team": "ATL", "OBP": 0.238},
    {"Rank": 163, "Player": "Lourdes Gurriel", "Team": "AZ", "OBP": 0.232},
    {"Rank": 164, "Player": "Jake Burger", "Team": "TEX", "OBP": 0.231},
    {"Rank": 165, "Player": "Josh Bell", "Team": "WSH", "OBP": 0.231},
    {"Rank": 166, "Player": "Michael Massey", "Team": "KC", "OBP": 0.217},
    {"Rank": 167, "Player": "Andrew Vaughn", "Team": "CWS", "OBP": 0.217},
    {"Rank": 168, "Player": "Taylor Ward", "Team": "LAA", "OBP": 0.215}
])


